# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI and CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:        
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: docker build . --file Dockerfile --tag ${{secrets.REGISTRY_HOST}}/studigo
      - name: Add commit tag
        run: docker tag ${{secrets.REGISTRY_HOST}}/studigo ${{secrets.REGISTRY_HOST}}/studigo:${{github.sha}}
      - name: Add latest tag
        run: docker tag ${{secrets.REGISTRY_HOST}}/studigo ${{secrets.REGISTRY_HOST}}/studigo:latest
      - name: Login to registry
        run: echo "${{secrets.REGISTRY_PASSWORD}}" | docker login -u ${{secrets.REGISTRY_USERNAME}} --password-stdin ${{secrets.REGISTRY_HOST}}
      - name: Push to registry
        run: docker push -a ${{secrets.REGISTRY_HOST}}/studigo
