# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI and CD

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
  
  unit-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Test
        run: cd StudiGO.Test && dotnet test --verbosity normal

  deploy:
    runs-on: ubuntu-latest
    needs: unit-test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Build docker image
        run: docker build . --file Dockerfile --tag ${{secrets.REGISTRY_HOST}}/studigo

      - name: Add commit tag
        run: docker tag ${{secrets.REGISTRY_HOST}}/studigo ${{secrets.REGISTRY_HOST}}/studigo:${{github.sha}}

      - name: Add latest tag
        run: docker tag ${{secrets.REGISTRY_HOST}}/studigo ${{secrets.REGISTRY_HOST}}/studigo:latest

      - name: Login to registry
        run: echo "${{secrets.REGISTRY_PASSWORD}}" | docker login -u ${{secrets.REGISTRY_USERNAME}} --password-stdin ${{secrets.REGISTRY_HOST}}

      - name: Push to registry
        run: docker push -a ${{secrets.REGISTRY_HOST}}/studigo
